### PR TITLE
Pass commands as list of args

### PR DESCRIPTION
**Pull request by terminalmage**
This should future-proof the code against future changes WRT python_shell=False

### CODE REVIEW

**Review by joe-niland — APPROVED** [review]
Thanks @terminalmage, this looks much cleaner.

**Comment by joe-niland** [comment]
I've tested with no issues.

**Comment by terminalmage** [comment]
Awesome, assuming tests are OK then we'll get https://github.com/saltstack/salt/pull/39628 merged. Thanks!

**Comment by joe-niland** [comment]
Great! Thanks for reviewing, @terminalmage

**Pull request merged**
